name: ci-docs
on:
  push:
    paths:
      - '**.md'
      - '**.mmd'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - uses: neenjaw/compile-mermaid-markdown-action@0.2.3
        with:
          files: 'docs/classdiagram.md'
          output: 'docs/imgs/'
      - run: mkdocs gh-deploy --force
